nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

changesetBaseRefs: ["main"]

packageExtensions:
  eslint-config-airbnb@^18.2.1:
    dependencies:
      eslint-plugin-jsx-a11y: ^6.4.1
      eslint-plugin-react-hooks: ^4

  eslint-config-airbnb-base@^14.2.1:
    dependencies:
      eslint: ^7.2.0
      eslint-plugin-import: ^2.22.1
  
  ts-node@^10.4.0:
    dependencies:
      "@types/node": "*"

    
